---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: egapro-crt
spec:
  secretName: egapro-crt-secret
  dnsNames:
  - ${ENVIRONMENT}
  - egapro-api.${ENVIRONMENT}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ${ENVIRONMENT}
      - egapro-api.${ENVIRONMENT}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
