---
kind: Pod
apiVersion: v1
metadata:
  name: egapro-init-kinto${HASH_BRANCH_NAME}
  labels:
    app: egapro-init-kinto
    branch: egapro-init-kinto${HASH_BRANCH_NAME}
spec:
  containers:
  - image: ${EGAPRO_REGISTRY}/kinto:${IMAGE_TAG}
    name: egapro-init-kinto
    env:
    - name: KINTO_BASE_URL
      value: "kinto${HASH_BRANCH_NAME}"
    - name: KINTO_ADMIN_LOGIN
      valueFrom:
        secretKeyRef:
          name: egapro-secret
          key: KINTO_ADMIN_LOGIN
    - name: KINTO_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: egapro-secret
          key: KINTO_ADMIN_PASSWORD
