---
apiVersion: v1
kind: Service
metadata:
  name: kinto${HASH_BRANCH_NAME}
  labels:
    app: kinto${HASH_BRANCH_NAME}
spec:
  type: NodePort
  ports:
  - port: 8888
  selector:
    app: kinto${HASH_BRANCH_NAME}
