---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: egapro-api
  labels:
    app: egapro-api
    branch: egapro
spec:
  rules:
  - host: egapro-api.${ENVIRONMENT}
    http:
      paths:
      - path: /
        backend:
          serviceName: egapro-api
          servicePort: ${PORT}
  tls:
  - secretName: egapro-crt-secret
