---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: egapro-app
  labels:
    app: egapro-app
    branch: egapro
spec:
  rules:
  - host: egapro.${ENVIRONMENT}.social.gouv.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: egapro-app
          servicePort: ${PORT}
  tls:
  - secretName: egapro-crt-secret
